server:
  port: 9002
  
spring:
  application:
    name: order
  rabbitmq:
    host: 192.168.10.76   
    username: fans
    password: 5128600
    port: 5672  
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone:  http://eurekaserver1:8000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
env: 我爱你 是来自灵魂来自生命的力量
      
