server:
  port: 9002
  
spring:
  application:
    name: order
eureka:
  client:
    service-url:
      defaultZone:  http://eurekaserver1:8000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
